### ISSUE TITLE
Code tour broken: process not found (in cq)

### ISSUE THREAD

**Issue by haikyuu** [githubnext/blocks-examples#79]
The code tour example uses https://github.com/fullstackio/cq as a dependency, and it crashes the block because of the error 
```
caught (in promise) ReferenceError: process is not defined
    at <anonymous>:225:8738
    at <anonymous>:21:540
    at <anonymous>:249:31896
    at BlockBundle (<anonymous>:261:1270)
    at $9 (index-9736b164.js:47:538)
    at j9 (index-9736b164.js:47:1437)
    at D9 (index-9736b164.js:47:1685)
    at o (i
```
The error happens in the deployed code as well as in development.

**Comment by haikyuu** [comment]
Also, Buffer is not defined as well. So I [installed it](https://github.com/feross/buffer)
